replicaCount: 2
#autoscaling:
#  enabled: false
#  minReplicas: "2"
#  maxReplicas: "4"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2
    memory: 1024Mi

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 8443
  
ingress:
  ## @param ingress.enabled Set to true to enable ingress record generation
  ##
  enabled: true
  hostname: dsp-golang-app-template-dsp-portal-usr-karl-nginx-proxy.dev.sp.dell.com
  path: /*
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: saas-dsp-portal-dev
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:eu-west-1:702886132326:certificate/aa01e3eb-053d-40c7-8f00-5f70741a3b3d'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
    alb.ingress.kubernetes.io/healthcheck-protocol: 'HTTP'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-path: /

  ingressClassName: "alb"

containerSecurityContext:
  runAsNonRoot: false

containerPorts:
  http: 8080
  https: 8443
  
serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://dsp-portal-gui:3000/;
    }
    location /agreement-svc {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://dsp-agreement-svc:5000/;
    }
    location /service-a {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://dsp-portal-service-a:5000/health;
    }
    location /service-b {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://dsp-portal-service-b:5000/health;
    }
    location /golang-template {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://dsp-golang-app-template:5000/health;
    }
  }
  
