name: Deploy 3rd Chart
run-name: "Deploy ${{ inputs.chart-name }} to ${{ inputs.cluster-name }} (values: ${{ inputs.values-file }})"
on:
  workflow_dispatch:
    inputs:
      chart-name:
        description: 3rd chart name (in ECR)
        type: string
        required: true
        default: neo4j-chart
      chart-version:
        description: 3rd chart version (in ECR)
        type: string
        required: true
        default: 0.2.0
      cluster-name:
        description: k8s cluster name
        type: string
        default: dell-eks-dev
        required: true
      namespace:
        description: k8s namespace name
        type: string
        required: true
        default: neo4j
      values-file:
        description: Chart values file
        type: string
        default: values.dev.yaml
        required: true

env:
  AWS_ROLE: >-    
    ${{ inputs.cluster-name == 'dell-eks-dev' && 'arn:aws:iam::702886132326:role/cfy-developers-github-actions-role'
    || inputs.cluster-name == 'cfy-eks-staging' && 'arn:aws:iam::816069151864:role/cfy-staging-github-actions-role'
    || inputs.cluster-name == 'cfy-eks-saas-prod' && 'arn:aws:iam::008791006138:role/cfy-production-github-actions-role'
    || inputs.cluster-name == 'cfy-eks-saas-prod-use1' && 'arn:aws:iam::008791006138:role/cfy-production-github-actions-role'
    }}

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: arc-runner-eks-small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: eu-west-1
    - name: Authenticate to EKS
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster-name }}
        echo "Successfully configured kubectl. Context is:"
        kubectl config current-context
    - name: Deploy to EKS
      run: |
        helm pull oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami/${{ inputs.chart-name}} --version ${{ inputs.chart-version }}
        tar -xzf ${{ inputs.chart-name}}-${{ inputs.chart-version }}.tgz --wildcards --no-anchored 'values.*' --transform='s|.*/||'  
        helm upgrade -i ${{ inputs.chart-name }} oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami/${{ inputs.chart-name}} --version ${{ inputs.chart-version }} \
           --create-namespace -n $${{ inputs.namespace }} --atomic --timeout 15m -f ${{ inputs.values-file }}