name: Package & Publish 3rd Chart
run-name: "Package & Publish ${{ inputs.chart-name }} chart"
on:
  push:
    branches:
      - usr/shayki/deploy-wf
  workflow_dispatch:
    inputs:
      chart-name:
        description: 3rd chart name (under "bitnami" folder)
        type: string
        required: true
      cluster-name:
        description: k8s cluster name
        type: string
        default: dell-eks-dev
        required: true

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: arc-runner-eks-small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::702886132326:role/cfy-developers-github-actions-role
        aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Deploy Chart
      working-directory: bitnami/neo4j
      run: |
        CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
        helm package -u --version $CHART_VERSION --dependency-update .
        helm push neo4j-$CHART_VERSION.tgz oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com