name: Sync fork with upstream main branch
run-name: "Sync fork with upstream main branch"
on:
  schedule:
    - cron: "0 0 * * *" # daily midnight
  workflow_dispatch:
   
jobs:
  sync_with_upstream:
    runs-on: arc-runner-eks-small
    name: Sync main with upstream latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        upstream_sync_repo: bitnami/charts
        upstream_sync_branch: main
        target_repo_token: ${{ secrets.AUTH_TOKEN_GITHUB_COM }}

    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "There were new commits."

    - name: Timestamp
      run: date

   
