name: Sync fork with upstream main branch
run-name: "Sync fork with upstream main branch"
on:
  schedule:
    - cron: "0 0 * * *" # daily midnight
  workflow_dispatch:
   
jobs:
  sync:

    runs-on: arc-runner-eks-small

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.AUTH_TOKEN_GITHUB_COM }}
          owner: korenlev
          base: main
          head: main   
